//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pipitos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comprobante_recoleccion
    {
        public int no_recibo { get; set; }
        public string recibimos_de { get; set; }
        public string a_nombre_de { get; set; }
        public string en_concepto_de { get; set; }
        public string entregado_por { get; set; }
        public string recibido_por { get; set; }
        public int id_donante { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual donante donante { get; set; }
    }
}
