//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pipitos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprobanteDesecho
    {
        public int iddesecho { get; set; }
        public int norecibo { get; set; }
        public int idmaterial { get; set; }
        public int cantidad { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual comprobante_recoleccion comprobante_recoleccion { get; set; }
        public virtual material material { get; set; }
    }
}
