//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class contacto
{
    public int id_contacto { get; set; }
    public string nombre_contacto { get; set; }
    public string num_telefono { get; set; }
    public string correo_electronico { get; set; }
    public string notas { get; set; }
}
