//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pipitos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pipitosEntities : DbContext
    {
        public pipitosEntities()
            : base("name=pipitosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<rutas> rutas { get; set; }
        public virtual DbSet<contacto> contacto { get; set; }
        public virtual DbSet<comprobante_recoleccion> comprobante_recoleccion { get; set; }
        public virtual DbSet<planificador_recoleccion> planificador_recoleccion { get; set; }
        public virtual DbSet<planificar_donante> planificar_donante { get; set; }
        public virtual DbSet<donante> donante { get; set; }
    }
}
