//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pipitos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class planificador_recoleccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public planificador_recoleccion()
        {
            this.planificar_donante = new HashSet<planificar_donante>();
        }
    
        public int id_plan_rec { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.DateTime> fechavisita { get; set; }
        public Nullable<bool> eliminada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<planificar_donante> planificar_donante { get; set; }
    }
}
