//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pipitos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recolecta
    {
        public int id_recolecta { get; set; }
        public Nullable<int> no_recibo { get; set; }
        public Nullable<int> id_material { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
    
        public virtual material material { get; set; }
        public virtual comprobante_recoleccion comprobante_recoleccion { get; set; }
    }
}
