//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pipitos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recolecta
    {
        public int id_recolecta { get; set; }
        public Nullable<int> no_recibo { get; set; }
        public Nullable<int> id_material { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
    
        public virtual material material { get; set; }
        public virtual comprobante_recoleccion comprobante_recoleccion { get; set; }
    }
}
