//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class rutas
{
    public int id_ruta { get; set; }
    public string nombre_ruta { get; set; }
    public string barrio { get; set; }
    public string distrito { get; set; }
    public string municipio { get; set; }
    public string departamento { get; set; }
}
